id: ICDD4FD1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:48:06+00:00'
last_modified: '2022-06-07T18:59:58.947544+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25213
  title: སྨོན་འདུན་གྱི་ལང་ཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '2057':
      image_group_id: I5809
      title: ''
      total_pages: 216
      order: 1
      base_file: 2057.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
