id: P003311
initial_creation_type: ocr
source_metadata:
  id: bdr:W25213
  title: སྨོན་འདུན་གྱི་ལང་ཚོ
  author: ''
  volumes:
    65284dbbeba64ed984db57f05378451e:
      image_group_id: I5809
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
